[package]
name = "mk-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mk-core.workspace = true
mk-vfs.workspace = true
axum = "0.8"
tokio = { version = "1", features = ["net", "rt", "io-util", "sync", "time"] }
futures-util = "0.3"
serde = { workspace = true }
uuid = { version = "1", features = ["v4"] }
